### PR TITLE
Add postcss alongside postcss-cli

### PR DESCRIPTION
**Pull request by sharksforarms**
See https://github.com/chabad360/hugo-gh-pages/issues/13

### CODE REVIEW

**Comment by chabad360** [comment]
Thanks for this.

Did you test that it indeed fixes the issue?

**Comment by sharksforarms** [comment]
Yes, for more context here is the breaking change in the changelog: https://www.github.com/postcss/postcss-cli/tree/master/CHANGELOG.md

**Comment by sharksforarms** [comment]
For the testing, I confirmed I was able to run `postcss -h` inside a built container

**Comment by chabad360** [comment]
Ah perfect! LGTM then! I'll manually trigger a rebuild in the other action either soon or tomorrow morning (probably the latter).

**Pull request merged**
